### ISSUE TITLE
CWL support for logging and storing: mounting working dir in tmp dir

### ISSUE THREAD

**Issue by MrGweep** [interTwin-eu/T6.5-AI-and-ML#28]
The current CWL support is limited to running the `v0.0` based on the MNIST dataset without logging or model storage. The `cwltool` gets invoked in the `/tmp` directory where it gets executed. If output files or directories are to be stored, they need to be specified in the `.cwl` file in order for the `cwltool` to link them to `/tmp`, i.e. creating directories on-the-fly with e.g. `os.mkdir()`, etc do not work.

Things to look into:
- find way to mount the working dir in the `/tmp` dir where execution happen
- otherwise adjust workflow and predefine files and directories (suboptimal solution)

**Comment by matbun** [comment]
note for the future: study the meaning of the `outputs` keywork (i.e., the "publishers")
